join_message: |-
  ───────────────────────
  {0}さん、
  ようこそ{1}へ！:tada: :hugging:
  雑談フォーラムは雑談に特化したDiscordサーバー。
  しかし、現状はほとんどのチャンネルが
  利用できないようになっています。
  <#515467524960157716> をよく読み、
  「アカウント登録」を
  済ませてからご参加ください！


  当サーバーに関する情報はこちらをご覧ください：
  https://chat-forum-dcc.jimdo.com/
  ──────────────────────
join_messages:
- '{0}がサーバーに飛び込んだ！カンガルーだ！'
- '{0}の参上だ！'
- '{0}が来た。しばらくの間、話を聞くのじゃ。'
- '{0}の登場だ。刮目せよ！'
- '{0}だ！トラップカード発動！'
- '{0}、そんな装備で大丈夫か？'
- '{0}はいいぞ。'
- '{0}が参加したってそマ！？'
- '{0}が来た！ワンチャンあるぞ。'
- '{0}が参加したンゴ。優しくするやで～。'
- '{0}がきっとくる～'
- '{0}、入ってる。'
- '{0}のフレンズなんだね～！すっごーい！'
- '{0}はこのサーバーにいるのさ！'
- '{0}君、やぁ。ピザは持ってきたよね？'
- '{0}が来た。あいつチートだろ...弱体修正まだ？'
- '{0}、Come on baby Chat forum～！'
- '{0}(水属性)がとびだしてきた！'
- '{0}、みんなあなたを待っていた！'
- '{0}に任せて！'
- '{0}が来たぞ。お遊びは終わりだ。'
- '{0}さん、ようこそ。武器はドアのそばに置いていってね。'
- '{0}、ゆっくりしていってね！'
- '{0}、もっと！熱くなれよ！'
- '{0}と共にあらんことを。'
- '{0}が帰還した！お疲れ様！'
- その、雑談フォーラムの中に、さらに、入ってきたのが{0}です。
- '{0}にもっと注目するといいと、{1}も思います'
- あれは、{0}、{0}マーン、{0}マーン
voice_text:
    "515467645684809748": 515467627209031690
    "515467647341821963": 515467629176029197
    "515467649564672020": 515467631176974336
    "515467651691315220": 515467633282383882
    "515467653712707594": 515467635345981440
    "515467655378108417": 515467636994473985
    "515467658053943297": 515467639229775874
    "515467660067209227": 515467643285667840
free_categories: []
kuina:
- "てんしーてんしーてんしてんしてんし"
- "くいなはーてんしー"
- "みんなのてんしー"
- "ざつふぉのてんしー"
- "昇天するぞー昇天するぞー昇天するぞ昇天するぞー"
- "だてんしーだてんしーだてんしだてんしだてんし"
- "へんたいーへんたいーへんたいー"
- "ちょっと変態な感じ、するぅ・・・堕天使なのがくいなです。"
hyouga:
- "『私は思ったことを言うよ』"
- "『無理しないでほしい』"
- "『円卓の鬼神(みなさん)！　幸運を祈ります！』"
- "『すごく……テンション荒ぶっております』"
- "『荒ぶる私です(｜｜三｜｜)ﾋｭﾝﾋｭﾝ』"
- "『(o;－－)ﾌｪ-…』"
- "『(o｜｜)ﾌｪ』"
- "『Σ(｜｜；)ﾌｪ!?』"
- "『(o｜｜)ﾌｪ?』"
- "『( ｜｜)o彡°ローウェン！　ローウェン！』"
- "『ど　う　し　て　こ　う　な　っ　た　し』"
- "『まったり行こうじゃないか～』"
- "『眠いよぅ』"
- "『ふにゃ～……』"
- "『あなた()と私はズットモです』"
- "『おばけだぞーい』"
- "『うぇーい』"
- "『(｜＜)ﾃﾍﾍﾟﾛ』"
- "『( っ｜｜)╮-=ﾆ=一＝三＝│二二二＞』"